version: '3.8'
services:
    db_news_write:
        build:
            context: ./infrastructure/db_news_write
        container_name: cnt_db_news_write
        image: img_db_news_write
        environment:
            - ACCEPT_EULA=Y
        ports:
            - "3005:5432"
    
    db_news_read:
        build:
            context: ./infrastructure/db_news_read
        container_name: cnt_db_news_read
        image: img_db_news_read
        restart: always
        ports:
            - "3006:27017"

    mongodb_gui:
        image: mongo-express
        restart: always
        ports:
            - 3007:8081 # mongodb gui
        environment:
            # - ME_CONFIG_MONGODB_URL="mongodb://admin:admin@localhost:3006/db?ssl=false"
            - ME_CONFIG_MONGODB_SERVER=db_news_read
            - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=admin
        depends_on:
            - db_news_read
    
    news_write:
        build:
            context: ./be-write/be-write
        container_name: cnt_news_write
        image: img_news_write
        ports:
            - "5000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development

    news_read:
        build:
            context: ./be-read
        container_name: cnt_news_read
        image: img_news_read
        ports:
            - "5002:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development

    news_sync:
        build:
            context: ./be-sync
        container_name: cnt_news_sync
        image: img_news_sync
        environment:
            - ASPNETCORE_ENVIRONMENT=Development